console.log(Number.MAX_VALUE);

console.log(Number.MAX_SAFE_INTEGER);

var students = [
    "Chris Ridder",
    "Ian Meyer",
    "wyatt domanski",
    "Jack Kok-Carlson",
    "Calkum Jelyse",
    "Davis Genthner",
    "Ty Clark",
    "Steven N. Zepeda",
    "Michael le parc",
    "Helen Evans",
    "Wade Fauth",
    "Zachary Stanaford",
    "Ramirez solis nguyen Julieta",
    "Sahen",
    "Zac Shedd",
    "Reagan Ilgenfritz",
    "Savannah Vel",
    "haydendillon-lloyd",
    "Garbe Carson",
    "Morris Nick",
    "Bowman Matthew",
    "Ethan Willers",
    "ap",
    "Nelson John",
    "matthewdelgado",
    "Faith Monzon",
    "Smith BJ",
    "Samantha Stark",
    "Jensen Sam",
    "Meyers Scott",
    "Ramirez Islas Carolina",
    "Jenn Scherschligt",
    "peter ataras",
    "Dan Dalton",
    "Mengler Patrick",
    "Pineda Sharmaine",
    "Maddie Gillis"
]